cc_test(
    name = "router_test",
    size = "small",
    srcs = ["router_test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/io:io",
        "//src/routing:routing",
        "//src/clock:clock",
    ],
)