cc_test(
    name = "io_test",
    size = "small",
    srcs = ["io_test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/io:io",
        "//src/rng:rng",
        "//src/clock:clock",
    ],
)