load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "state",
    srcs = ["state.cc"],
    hdrs = ["state.h"],
    deps = [
        "//src/node",
    ],
    visibility = ["//visibility:public"],
)
