load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "routing",
    srcs = [],
    hdrs = ["router.h"],
    deps = [
        "//src/io:io",
        "//src/system:system",
        "//src/node:node",

    ],
    visibility = ["//visibility:public"],
)