cc_test(
    name = "system_test",
    size = "small",
    srcs = ["system_test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/io:io",
        "//src/rng:rng",
        "//src/clock:clock",
        "//src/system:system",
    ],
)